// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MusicClassifierML.Model
{
    public class ModelInput
    {
        [ColumnName(":ID(Artist)"), LoadColumn(0)]
        public string _ID_Artist_ { get; set; }


        [ColumnName("name"), LoadColumn(1)]
        public string Name { get; set; }


        [ColumnName(":LABEL"), LoadColumn(2)]
        public string _LABEL { get; set; }


    }
}
