using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sciendo.MusicClassifier.KnowledgeBaseProvider.Generators
{
    public class ExcludesLoaded
    {
        public string[] NonTitledInformationFromTitle = new[]
        {
                @"\(.?\)",
                @"\(part \d*\)",
                @"\(\d*\)",
                "(live)",
                "(instrumental)",
                "(original mix)"
            };
        public string[] FeaturedMarkers = new[] { "(", ")" };

        public string PlaceholderAlbumArtists = "Various Artists";

        public char[] CharactersSeparatorsForWords = new[] { ',', '/', ';', ':'};

        public string[] WordsSeparatorsGlobal = new[]
        {
                "arr.",
                "by",
                "ch",
                "con",
                "demo",
                "edit",
                "extended",
                "feat",
                "featuring",
                "feat.",
                "ft.",
                "instrumental",
                "main",
                "mix",
                "mixed",
                "orch.",
                "original",
                "part",
                "presents",
                "pres.",
                "prod.",
                "radio",
                "remix",
                "remixed",
                "theme",
                "version",
                "vocal",
                "vocals",
                "vs",
                "vs.",
                "with",
                "x",
                "✖",
            };

        public string[] ArtistsForSplitting = new[]
        {
                "2pac",
                "alvin pleasant delaney carter",
                "anna of the north",
                "antonio carles marques pinto",
                "aram mp3",
                "armistead burwell smith iv",
                "arvo part",
                "b l a c k i e",
                "boydston john d. iii",
                "D'Angelo Lacy",
                "Dolores O'Riordan",
                "jennifer evans van der harten",
                "john 5",
                "K-$",
                "kh of moscrill",
                @"luther ""guitar junior"" johnson",
                "maria isabel garcia asensio",
                "Mary Margaret O'Hara",
                "michael l. williams ii",
                "michiel van der kuy",
                "Possessed by Paul James",
                "the reverend peyton",
                "Ta'Raach",
            };

        public string[] BandsForSplitting = new[]
        {
                "60,000,000 Buffalo",
                "AC/DC",
                "AC; DC",
                "Artist Vs Poet",
                "Astronauts, etc.",
                "Benny Turner and Real Blues",
                "Bird by Bird",
                "Bizkit with Butta On the Keytar",
                "The Black & White Years",
                "Boy Meets Girl",
                "Blood, Sweat & Tears",
                "Brighton, MA",
                "Built By Snow",
                "Can 7",
                "Con Brio",
                "Conga Radio",
                "Creature With The Atom Brain",
                "Crosby, Stills, Nash & Young",
                "Damian Cowell's Disco Machine",
                "Dance With the Dead",
                "Death By Unga Bunga",
                "Der Original Schintl",
                "Die original Ochsenfurter Blasmusik",
                "Dr. Bobby Banner, MPC",
                "Drive-By Truckers",
                "Driving By Night",
                "Drop Dead, Gorgeous",
                "Earth, Wind & Fire",
                "Elana James and Her Hot, Hot Trio",
                "Emerson, Lake & Palmer",
                "Ex:Re",
                "Fighting With Wire",
                "Followed By Static",
                "Gina X Performance",
                "Girls Guns and Glory",
                "Good Night & Good Morning",
                "The Good, The Bad and The Queen",
                "Goombay Dance Band",
                "Hi, Brits",
                "I'm a Lion, I'm a Wolf",
                "Jackie's Boy",
                "Kawai, Mal Duo",
                "Kitty, Daisy & Lewis",
                "Kowton's Feeling Fragile",
                "Kunstner 5",
                "The Last Artful, Dodgr",
                "Lorelle Meets The Obsolete",
                "Love X Stereo",
                "The Main Ingredient",
                "The Main Squeeze",
                "The Main Street Gospel",
                "Maroon 5",
                "Martha and the Muffins",
                "Murder By Death",
                "Myka 9",
                "Nostalgia 77 Octet",
                "nothing,nowhere.",
                "Now, Now",
                "Obscured By Echoes",
                "Oh,Beast!",
                "Oh, Rose",
                "Or, the Whale",
                "Part 1",
                "Part-Time Friends",
                "Part Time",
                "Peter, Bjorn and John",
                "Pets With Pets",
                "Prefuse 73",
                "Project Jenny, Project Jan",
                "Quien es, Boom!",
                "Radio B.",
                "Sex With Strangers",
                "Shy, Low",
                "Shot x Shot",
                "Some By Sea",
                "Something With Numbers",
                "Stella By Starlight",
                "Stoni Taylor & Miles Of Stones",
                "Super Onze, The Takamba champions of the Niger bend.",
                "Swimming With Bears",
                "Swimming With Dolphins",
                "Tacks, the Boy Disaster",
                "Take 6",
                "Take Over And Destroy",
                "Thieves by the Code",
                "The Thing With Five Eyes",
                "To Live And Die In LA",
                "T'nah Apex",
                "Tyler, The Creator",
                "Up, Bustle And Out",
                "Us, Today",
                "X Ambassadors",
                "You, Me, And Everyone We Know",
            };
    }
}
